libraryDependencies += "org.typelevel" %% "cats" % "0.5.0"
libraryDependencies += "com.chuusai" %% "shapeless" % "2.3.1-SNAPSHOT"
libraryDependencies += "co.fs2" %% "fs2-core" % "0.9.0-SNAPSHOT"
libraryDependencies += "co.fs2" %% "fs2-cats" % "0.1.0-SNAPSHOT"
libraryDependencies += "org.typelevel" %% "kittens" % "1.0.0-M3"
